# -*- coding: utf-8 -*-
#
# Copyright (c) 2024, Geoffrey M. Poor
# Copyright (c) 2024, Gary Clarke
# All rights reserved.
#
# Licensed under the BSD 3-Clause License:
# http://opensource.org/licenses/BSD-3-Clause
#


import datetime
from typing import List, Dict, Optional
from ..quiz import Image


MANIFEST_START = '''\
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 http://www.imsglobal.org/xsd/qti/qtiv2p1/qtiv2p1_imscpv1p2_v1p0.xsd
                      http://www.imsglobal.org/xsd/imsqti_v2p2 http://www.imsglobal.org/xsd/qti/qtiv2p1/imsqti_v2p2p4.xsd
                      http://www.imsglobal.org/xsd/imsqti_metadata_v2p2 http://www.imsglobal.org/xsd/qti/qtiv2p1/imsqti_metadata_v2p2.xsd
                      http://ltsc.ieee.org/xsd/LOM http://www.imsglobal.org/xsd/imsmd_loose_v1p3p2.xsd
                      http://www.w3.org/1998/Math/MathML http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd"
  identifier="{manifest_identifier}">
  <metadata>
    <schema>QTIv2.2 Package</schema>
    <schemaversion>1.0.0</schemaversion>
  </metadata>
  <organizations/>
  <resources>
    <resource identifier="{assessment_identifier}" type="imsqti_test_xmlv2p1" href="{assessment_identifier}.xml">
      <metadata>
        <lom xmlns="http://ltsc.ieee.org/xsd/LOM">
          <general>
            <identifier>
              <entry>{assessment_identifier}</entry>
            </identifier>
            <title>
              <string language="en">QTI assessment generated by text2qti</string>
            </title>
          </general>
          <lifeCycle>
            <contribute>
              <date>
                <dateTime>{date}}</dateTime>
              </date>
            </contribute>
          </lifeCycle>
          <educational>
            <learningResourceType>
              <source>QTIv2.2</source>
              <value>ExaminationTest</value>
            </learningResourceType>
          </educational>
        </lom>
      </metadata>
      <file href="{assessment_identifier}/assessment_meta.xml"/>
'''

DEPENDENCY = '''\
      <dependency identifierref="{dependency_identifier}"/>
'''

MANIFEST_MIDDLE = '''\
    </resource>
'''

RESOURCE = '''\
    <resource identifier="{dependency_identifier}" type="imsqti_item_xmlv2p2" href="{dependency_identifier}.xml">
      <file href="{dependency_identifier}.xml"/>
    </resource>
'''

MANIFEST_END = '''\
  </resources>
</manifest>
'''


def imsmanifest(*,
                manifest_identifier: str,
                assessment_identifier: str,
                dependency_identifiers: List[str],
                date: Optional[str] = None) -> str:
    '''
    Generate `imsmanifest.xml`.
    '''
    if date is None:
        date = str(datetime.date.today())
    xml = []
    xml.append(MANIFEST_START.format(manifest_identifier=manifest_identifier,
                                     assessment_identifier=assessment_identifier,
                                     date=date))
    for dependency_identifier in dependency_identifiers:
        xml.append(DEPENDENCY.format(dependency_identifier=dependency_identifier))
    xml.append(MANIFEST_MIDDLE)
    for dependency_identifier in dependency_identifiers:
        xml.append(RESOURCE.format(dependency_identifier=dependency_identifier))
    xml.append(MANIFEST_END)
    return ''.join(xml)
